import React, { useState } from 'react';
import { useAuth } from '../../contexts/AuthContext';
import { Smartphone, Lock, ArrowRight } from 'lucide-react';
import toast from 'react-hot-toast';

const MFAModal = ({ mfaToken, onComplete, onCancel }) => {
  const { loginMFA } = useAuth();
  const [code, setCode] = useState('');
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (code.length !== 6) return toast.error('Please enter a 6-digit code');

    setLoading(true);
    const result = await loginMFA(mfaToken, code);
    setLoading(false);

    if (result.success) {
      onComplete();
    }
  };

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 sm:p-6">
      {/* Backdrop */}
      <div 
        className="absolute inset-0 bg-slate-950/80 backdrop-blur-sm animate-in fade-in duration-300"
        onClick={onCancel}
      />
      
      {/* Modal */}
      <div className="relative w-full max-w-md bg-slate-900 border border-slate-800 rounded-2xl shadow-2xl overflow-hidden animate-in zoom-in-95 duration-300">
        <div className="p-8">
          <div className="flex flex-col items-center text-center mb-8">
            <div className="w-16 h-16 bg-blue-500/10 text-blue-400 rounded-2xl flex items-center justify-center mb-4 rotate-3">
              <Smartphone size={32} />
            </div>
            <h2 className="text-2xl font-bold text-white mb-2">Two-Step Verification</h2>
            <p className="text-slate-400 text-sm">
              Enter the 6-digit verification code generated by your authenticator app.
            </p>
          </div>

          <form onSubmit={handleSubmit} className="space-y-6">
            <div className="relative">
              <div className="absolute inset-y-0 left-0 pl-4 flex items-center pointer-events-none text-slate-500">
                <Lock size={18} />
              </div>
              <input
                type="text"
                maxLength="6"
                placeholder="000 000"
                value={code}
                onChange={(e) => setCode(e.target.value.replace(/\D/g, ''))}
                className="w-full bg-slate-800/50 border border-slate-700 focus:border-blue-500 rounded-xl py-4 pl-12 pr-4 text-center text-2xl tracking-[0.5em] text-white focus:outline-none focus:ring-4 focus:ring-blue-500/10 transition-all font-mono"
                autoFocus
              />
            </div>

            <button
              type="submit"
              disabled={loading || code.length !== 6}
              className="w-full group relative py-4 bg-blue-600 hover:bg-blue-500 disabled:opacity-50 disabled:cursor-not-allowed text-white rounded-xl font-bold transition-all shadow-lg shadow-blue-600/20 overflow-hidden"
            >
              <div className="relative z-10 flex items-center justify-center gap-2">
                {loading ? 'Verifying...' : 'Verify Identity'}
                {!loading && <ArrowRight size={18} className="group-hover:translate-x-1 transition-transform" />}
              </div>
              <div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/10 to-transparent -translate-x-full group-hover:animate-shimmer" />
            </button>

            <button
              type="button"
              onClick={onCancel}
              className="w-full py-2 text-slate-500 hover:text-slate-300 text-sm transition-colors"
            >
              Cancel and try another method
            </button>
          </form>
        </div>
        
        {/* Footer info */}
        <div className="bg-slate-800/30 p-4 border-t border-slate-800 text-center">
          <p className="text-xs text-slate-500">
            Secure authentication provided by MISC Pro Security Engine
          </p>
        </div>
      </div>
    </div>
  );
};

export default MFAModal;

